FROM node:16-alpine

WORKDIR /app

# Add these lines to help with troubleshooting
ENV NODE_OPTIONS="--max-old-space-size=4096"
ENV CI=false
ENV ESLINT_NO_DEV_ERRORS=true

COPY package*.json ./

RUN npm install

# Copy source files
COPY . .

# Expose development port
EXPOSE 3000

# Start in development mode
CMD ["npm", "start"]
