version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: pocketpro-backend-dev
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=1
      - PORT=5000
      - CHROMADB_HOST=chromadb
      - CHROMADB_PORT=8000
      - FRONTEND_URL=http://localhost:3000
      - SQLALCHEMY_DATABASE_URI=sqlite:////app/app.db
    volumes:
      - .:/app
      - ./uploads:/app/uploads
      - ./chromadb_data:/app/chromadb_data
      - ./logs:/app/logs
    restart: unless-stopped
    command: python run.py

  chromadb:
    image: chromadb/chroma:latest
    container_name: chromadb-dev
    ports:
      - "8000:8000"
    volumes:
      - ./chromadb_data:/chroma/chroma
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=8000
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/chroma/chroma
    restart: unless-stopped

networks:
  default:
    name: pocketpro-dev-network
