version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.frontend.render
    ports:
      - "10000:80"
    depends_on:
      - backend
    environment:
      - BACKEND_URL=backend:$PORT

  backend:
    build:
      context: .
      dockerfile: Dockerfile.render.full
    image: pocketpro-sba-backend
    container_name: pocketpro-sba-backend
    environment:
      - PORT
      - FLASK_ENV=production
      - FLASK_APP=app_full.py
    # Ports mapping removed - not needed for Render private services
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:$PORT/health"]
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 5s
    restart: unless-stopped
    command: /bin/sh -c "gunicorn --bind 0.0.0.0:$PORT --timeout 60 app_full:app"

