version: '3'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.debug
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - REACT_APP_BACKEND_URL=http://localhost:10000
      - CHOKIDAR_USEPOLLING=true
    command: npm start
    
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1

  nginx:
    image: nginx:alpine
    ports:
      - "10000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
