version: '3.8'
services:
  chromadb:
    image: chromadb/chroma:latest
    container_name: chromadb
    volumes:
      - ./chromadb_data:/data
    ports:
      - "8000:8000"
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend.prod
    depends_on:
      - chromadb
    env_file:
      - .env.example
    ports:
      - "5000:5000"
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend.prod
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped

networks:
  default:
    name: app-network
