version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.render
    image: pocketpro-sba-backend
    container_name: pocketpro-sba-backend
    environment:
      - PORT=${PORT:-5000}
      - FLASK_ENV=production
      - FLASK_APP=minimal_app.py
    ports:
      - "${PORT:-5000}:${PORT:-5000}"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT:-5000}/health"]
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 5s
    restart: unless-stopped
    command: gunicorn --bind 0.0.0.0:${PORT:-5000} --timeout 60 minimal_app:app
