services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5000:5000"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - FLASK_ENV=production
      - CHROMA_HOST=chromadb
      - CHROMA_PORT=8000
    volumes:
      - ./uploads:/app/uploads
      - ./chromadb_data:/app/chromadb_data
    depends_on:
      - chromadb
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "10000:80"
    depends_on:
      - backend
    networks:
      - app-network

  chromadb:
    image: ghcr.io/chroma-core/chroma:0.6.0
    ports:
      - "8000:8000"
    volumes:
      - ./chromadb_data:/chroma/chroma
    environment:
      - CHROMA_HOST=0.0.0.0
      - CHROMA_PORT=8000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
