services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.production
    container_name: pocketpro-backend
    ports:
      - "${PORT:-5000}:5000"
    environment:
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
      - PORT=5000
      - CHROMADB_HOST=chromadb
      - CHROMADB_PORT=8000
      - FRONTEND_URL=http://frontend:80
    env_file:
      - backend/.env
    volumes:
      - ./uploads:/app/uploads
      - ./chromadb_data:/app/chromadb_data
      - ./logs:/app/logs
    restart: unless-stopped
    depends_on:
      - chromadb
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  chromadb:
    image: chromadb/chroma:latest
    container_name: chromadb-production
    ports:
      - "8000:8000"
    volumes:
      - ./chromadb_data:/chroma/chroma
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=8000
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/chroma/chroma
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/heartbeat"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  frontend: # New frontend service
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: pocketpro-frontend
    ports:
      - "3000:80" # Map host port 3000 to container port 80 (nginx default)
    environment:
      - REACT_APP_API_URL=http://backend:5000 # Point to the backend service
    depends_on:
      - backend # Frontend depends on backend
    restart: unless-stopped

networks:
  default:
    name: pocketpro-network