# Simplified Production Docker Compose for PocketPro:SBA Edition
services:
  # Backend API Service
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - FLASK_APP=run.py
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - SECRET_KEY=${SECRET_KEY:-default_secret_key_change_in_production}
    volumes:
      - ./uploads:/app/uploads
      - ./chromadb_data:/app/chromadb_data
      - ./logs:/app/logs
    networks:
      - app-network
    restart: unless-stopped

  # Frontend Web Service
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend.simple
    ports:
      - "80:80"
      - "3000:80"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:5000
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
