version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.render.full
    image: pocketpro-sba-backend
    container_name: pocketpro-sba-backend
    environment:
      - PORT=${PORT:-5000}
      - FLASK_ENV=production
      - FLASK_APP=app_full.py
    # Ports mapping removed - not needed for Render private services
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT:-5000}/health"]
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 5s
    restart: unless-stopped
    command: gunicorn --bind 0.0.0.0:${PORT:-5000} --timeout 60 app_full:app

  web:
    build:
      context: .
      dockerfile: Dockerfile.frontend.render
    ports:
      - "10000:80"
    depends_on:
      - backend
    environment:
      - BACKEND_URL=backend:${PORT:-5000}
