version: '3.8'

services:
  backend-minimal:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - /tmp:/tmp
      - backend_tmpfs:/dev/shm
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=true
      - PORT=5000
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    command: python minimal_app.py
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    networks:
      - app-network

  frontend-minimal:
    build:
      context: .
      dockerfile: Dockerfile.frontend.dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:5000
      - CI=false
      - ESLINT_NO_DEV_ERRORS=true
      - NODE_OPTIONS=--max-old-space-size=2048
      - GENERATE_SOURCEMAP=false
      - WDS_SOCKET_PORT=0
    deploy:
      resources:
        limits:
          memory: 3G
        reservations:
          memory: 1G
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  backend_tmpfs:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
