# .github/workflows/production-test.yml
#
# This GitHub Actions workflow automates the production testing plan.
# It runs the `run-production-tests.sh` script on every push or pull request
# to the main branch, ensuring the production deployment is always stable.

name: Production Deployment Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-production-deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create .env file for testing
        run: |
          echo "GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}" >> .env
          echo "SECRET_KEY=a-very-secure-secret-key-for-ci-testing" >> .env
          # For the self-contained test within the runner, this URL is correct.
          echo "REACT_APP_BACKEND_URL=http://localhost:5000" >> .env

      - name: Make test script executable
        run: chmod +x ./run-production-tests.sh

      - name: Run Production Test Script
        run: ./run-production-tests.sh