services:
  - type: docker
    name: pocketprosba-backend
    dockerfilePath: Dockerfile.production
    plan: standard
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 5000
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: minimal_app.py
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PYTHONDONTWRITEBYTECODE
        value: "1"
      - key: GEMINI_API_KEY
        value: ""         # Fill in Render UI
      - key: CHROMA_HOST
        value: "localhost"
      - key: CHROMA_PORT
        value: "8000"
      - key: UPLOAD_FOLDER
        value: "./uploads"
      - key: CHUNK_SIZE
        value: "500"
      - key: LOG_LEVEL
        value: "INFO"
      - key: SECRET_KEY
        generateValue: true
