services:
  - type: web
    name: pocketprosba-backend
    runtime: python
    repo: https://github.com/Adportfolionode/pocketprosba
    branch: main
    healthCheckPath: /api/info
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PORT
        value: "5000"
      - key: GEMINI_API_KEY
        sync: false
      - key: CHROMADB_HOST
        fromService:
          type: pserv
          name: chromadb
          property: host
      - key: CHROMADB_PORT
        fromService:
          type: pserv
          name: chromadb
          property: port
      - key: FRONTEND_URL
        value: "https://pocketprosba-frontend.onrender.com"
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "gunicorn 'backend.app:create_app()' --bind 0.0.0.0:$PORT"

  - type: web
    name: pocketprosba-frontend
    runtime: static
    repo: https://github.com/Adportfolionode/pocketprosba
    branch: main
    envVars:
      - key: REACT_APP_API_URL
        value: "https://pocketprosba-backend.onrender.com"
    buildCommand: "cd frontend && npm install && npm run build"

  - type: pserv
    name: chromadb
    runtime: docker
    repo: https://github.com/Adportfolionode/pocketprosba
    dockerfilePath: ./Dockerfile.chromadb
    plan: starter
    autoDeploy: true
    envVars:
      - key: CHROMA_SERVER_HOST
        value: 0.0.0.0
      - key: CHROMA_SERVER_HTTP_PORT
        value: "8000"
      - key: IS_PERSISTENT
        value: "TRUE"
      - key: PERSIST_DIRECTORY
        value: /data
    disk:
      name: chroma-data
      mountPath: /data
      sizeGB: 2
