# render.yaml
#
# This file defines the infrastructure for deploying the PocketPro:SBA application
# on Render.com. It has been consolidated from multiple versions to create a single,
# stable, and production-ready configuration.

services:
  # --------------------------------------------------
  # 1. ChromaDB Service (Dependency)
  # --------------------------------------------------
  - type: web
    name: chromadb
    runtime: docker
    image:
      url: chromadb/chroma:0.5.0
    plan: standard
    region: oregon
    healthCheckPath: /api/v1/heartbeat
    envVars:
      - key: CHROMA_SERVER_HOST
        value: 0.0.0.0

  # --------------------------------------------------
  # 2. Redis Service (Dependency for Scaling)
  # --------------------------------------------------
  - type: redis
    name: redis
    plan: standard
    region: oregon
    ipAllowList: []
    maxmemoryPolicy: allkeys-lru

  # --------------------------------------------------
  # 3. Backend API Service (Dependent)
  # --------------------------------------------------
  - type: web
    name: pocketpro-sba-app
    plan: standard
    numInstances: 1
    region: oregon
    runtime: docker
    dockerfilePath: ./Dockerfile.backend.multi
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis
          property: connectionString
      - key: CHROMA_HOST
        fromService:
          type: web
          name: chromadb
          property: host
      - key: CHROMA_PORT
        fromService:
          type: web
          name: chromadb
          property: port
      - key: GEMINI_API_KEY
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: CORS_ORIGINS
        value: "https://pocketprosba-frontend.onrender.com,http://localhost:3000"

  # --------------------------------------------------
  # 4. React Frontend Static Site Service
  # --------------------------------------------------
  - type: static
    name: pocketprosba-frontend
    env: static
    buildCommand: "cd frontend && npm install && npm run build"
    staticPublishPath: "frontend/build"
    envVars:
      - key: REACT_APP_API_URL
        value: "https://pocketpro-sba-app.onrender.com/api"
  
