services:
  - type: web
    name: pocketprosba-backend
    runtime: docker
    dockerfilePath: Dockerfile.render.full
    plan: standard
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 10000
      - key: GEMINI_API_KEY
        value: ""         # Fill in Render UI
      - key: CHROMA_HOST
        value: "backend"  # Changed from "localhost" to "backend"
      - key: CHROMA_PORT
        value: "8000"
      - key: UPLOAD_FOLDER
        value: "./uploads"
      - key: CHUNK_SIZE
        value: "500"
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: LOG_LEVEL
        value: "INFO"
      - key: FLASK_ENV
        value: "production"
      - key: SECRET_KEY
        generateValue: true

  - type: web
    name: pocketprosba-frontend
    env: node
    branch: main
    plan: free
    buildCommand: cd frontend && npm install --legacy-peer-deps --include=dev && npm run build
    startCommand: npx serve -s frontend/build -l $PORT
    envVars:
      - key: PORT
        value: "10000"
      - key: REACT_APP_BACKEND_URL
        value: https://pocketprosba-backend.onrender.com
