services:
  - type: web
    name: pocketpro-frontend
    env: static
    buildCommand: docker build -f Dockerfile.frontend.prod -t pocketpro-frontend-prod .
    staticPublishPath: /usr/share/nginx/html
    healthCheckPath: /
    envVars:
      - key: REACT_APP_BACKEND_URL
        value: https://pocketprosba-backend.onrender.com/api/
      - key: GEMINI_API_KEY
        value: your_gemini_api_key

  - type: web
    name: pocketpro-backend
    env: docker
    dockerfilePath: Dockerfile.production
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: "3.9"
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: app_full.py
      - key: PORT
        value: "5000"
      - key: SECRET_KEY
        generateValue: true
      - key: CORS_ORIGINS
        value: "*"
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: CHROMADB_URL
        value: http://chromadb:8000
      - key: GEMINI_API_KEY
        value: your_gemini_api_key
      - key: REDIS_URL
        value: redis://localhost:6379/0
      - key: LOG_LEVEL
        value: INFO
      - key: RAG_SYSTEM_ENABLED
        value: "true"
      - key: UPLOAD_FOLDER
        value: ./uploads

  - type: web
    name: pocketpro-nginx
    env: docker
    dockerfilePath: Dockerfile.frontend.prod
    healthCheckPath: /
    envVars:
      - key: NGINX_CONFIG
        value: nginx.prod.conf
