services:
  - type: web
    name: pocketpro-frontend
    env: static
    buildCommand: docker build -f Dockerfile.frontend.prod -t pocketpro-frontend-prod .
    staticPublishPath: /usr/share/nginx/html
    healthCheckPath: /
    envVars:
      - key: REACT_APP_BACKEND_URL
        value: https://pocketprosba-backend.onrender.com/api/
      - key: GEMINI_API_KEY
        value: your_gemini_api_key

  - type: web
    name: pocketpro-backend
    env: docker
    dockerfilePath: Dockerfile.backend.prod
    healthCheckPath: /health
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 10000
      - key: CHROMADB_URL
        value: http://chromadb:8000
      - key: GEMINI_API_KEY
        value: your_gemini_api_key

  - type: web
    name: pocketpro-nginx
    env: docker
    dockerfilePath: Dockerfile.frontend.prod
    healthCheckPath: /
    envVars:
      - key: NGINX_CONFIG
        value: nginx.prod.conf