services:
  # Backend API Service (Primary Application)
  - type: web
    name: pocketpro-sba-backend
    runtime: python
    buildCommand: pip install --upgrade pip setuptools wheel && pip install -r requirements-render-minimal.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --timeout 60 --workers 2 --access-logfile - --error-logfile - minimal_app:app
    plan: starter
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: minimal_app.py
      - key: PORT
        value: 5000
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHONPATH
        value: /opt/render/project/src:/opt/render/project
      - key: CORS_ORIGINS
        value: "*"
      - key: PYTHONUNBUFFERED
        value: "1"
    healthCheckPath: /health
    healthCheckTimeout: 15
    autoDeploy: false
    numInstances: 1

  # Frontend Static Site
  - type: static
    name: pocketpro-sba-frontend
    buildCommand: cd frontend && npm install --legacy-peer-deps && npm run build
    staticPublishPath: frontend/build
    pullRequestPreviewsEnabled: false
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: REACT_APP_BACKEND_URL
        fromService:
          type: web
          name: pocketpro-sba-backend
          property: host
