services:
  - type: web
    name: pocketpro-sba-app
    runtime: docker
    dockerfilePath: ./Dockerfile.optimized
    plan: standard
    autoDeploy: true
    healthCheckPath: /health

  - type: web
    name: pocketprosba-frontend
    runtime: static
    buildCommand: "cd frontend && npm ci --legacy-peer-deps && npm run build"
    autoDeploy: true
    envVars:
      - key: REACT_APP_API_URL
        value: "https://pocketpro-sba-app.onrender.com/api"
