# render.yaml
services:
  - type: web             # Python/Flask backend
    name: pocketprosba-backend
    env: python
    branch: main
    plan: free
    buildCommand: pip install --no-cache-dir -r requirements-full.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT run:app
    envVars:
      - key: GEMINI_API_KEY
        value: ""         # ← you’ll fill this in Render UI
      - key: CHROMA_HOST
        value: "localhost"
      - key: CHROMA_PORT
        value: "8000"
      - key: UPLOAD_FOLDER
        value: "./uploads"
      - key: CHUNK_SIZE
        value: "500"

    - type: web             # React frontend
    name: pocketprosba-frontend
    env: node
    branch: main
    plan: free
    buildCommand: cd frontend && npm install --legacy-peer-deps && npm run build
    startCommand: serve -s frontend/build -l $PORT
    envVars:
      - key: REACT_APP_BACKEND_URL
        value: ""         # ← fill in Render UI
