# render.yaml
#
# This file defines the infrastructure for deploying the PocketPro:SBA application
# on Render.com. It specifies two services: a backend web service that also
# serves the frontend, and a private ChromaDB service for the vector store.

services:
  # --------------------------------------------------
  # Backend Service (Python/Flask API + React Frontend)
  # --------------------------------------------------
  - type: web
    name: pocketpro-sba-app
    plan: starter
    region: oregon
    runtime: docker
    dockerfilePath: ./Dockerfile.render.full
    # This command starts the production server, which serves both the API and the frontend.
    # It is aligned with the CMD in the Dockerfile for consistency.
    # Added --timeout for long-running AI tasks and aligned with best practices.
    dockerCommand: gunicorn --bind 0.0.0.0:$PORT --worker-class eventlet -w 1 --timeout 120 app_full:app
    healthCheck:
      path: /health
      initialDelaySeconds: 60
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT # Explicitly define the port for clarity, though Render injects it.
        value: 10000
      - key: PYTHONUNBUFFERED # Ensures logs are sent directly to the console for real-time viewing.
        value: "1"
      - key: CHROMA_HOST
        fromService:
          type: pserv
          name: chromadb
          property: host
      - key: CHROMA_PORT
        fromService:
          type: pserv
          name: chromadb
          property: port
      - fromGroup: pocketpro-secrets

  # --------------------------------------------------
  # ChromaDB Private Service
  # --------------------------------------------------
  - type: pserv
    name: chromadb
    plan: starter
    region: oregon
    runtime: docker
    dockerImageName: chromadb/chroma:0.5.0 # Pin to a specific version for stability
    # Render Disks are required for data persistence
    disks:
      - name: chromadb-data
        mountPath: /chroma/chroma
        sizeGB: 1 # Note: Consider increasing size for larger document collections.
    port: 8000 # Explicitly declare the internal port for ChromaDB.
    healthCheck:
      path: /api/v1/heartbeat
      initialDelaySeconds: 40

envVarGroups:
  - name: pocketpro-secrets
    envVars:
      - key: GEMINI_API_KEY
      - key: SECRET_KEY
        generateValue: true # Let Render generate a secure random string