services:
  # Backend API Service
  - type: web
    name: pocketpro-sba-backend
    runtime: python
    buildCommand: pip install -r requirements-render.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers=2 --threads=4
    plan: standard
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: CHROMA_HOST
        fromService:
          type: web
          name: chromadb
          property: host
      - key: CHROMA_PORT
        fromService:
          type: web
          name: chromadb
          property: port

  # Frontend React Application
  - type: web
    name: pocketpro-sba-frontend
    runtime: static
    buildCommand: cd frontend && npm ci && npm run build
    staticPublishPath: frontend/build
    plan: starter
    autoDeploy: true
    envVars:
      - key: REACT_APP_API_URL
        value: https://pocketpro-sba-backend.onrender.com

  # ChromaDB Vector Database
  - type: web
    name: chromadb
    runtime: docker
    image:
      url: chromadb/chroma:0.5.0
    plan: standard
    autoDeploy: true
    healthCheckPath: /api/v1/heartbeat
    envVars:
      - key: CHROMA_SERVER_HOST
        value: 0.0.0.0
      - key: CHROMA_SERVER_HTTP_PORT
        value: 8000
