services:
  # Frontend Static Site
  - type: web
    name: pocketpro-sba-frontend
    env: node
    buildCommand: npm install && npm run build
    startCommand: serve -s build
    envVars:
      - key: REACT_APP_API_URL
        value: "https://<your-backend-service-name>.onrender.com"
    routes:
      - type: rewrite
        source: /api/(.*)
        destination: https://<your-backend-service-name>.onrender.com/api/$1
      - type: static
        source: /
        destination: /

  # Backend API Service (Primary Application)
  - type: web
    name: pocketpro-sba-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
        value: "1"
    healthCheckPath: /health
    healthCheckTimeout: 30
    autoDeploy: false
    numInstances: 1
