services:
  # Frontend Static Site
  - type: web
    name: pocketpro-sba-frontend
    env: node
    buildCommand: npm install && npm run build
    startCommand: serve -s build
    envVars:
      - key: REACT_APP_API_URL
        value: "https://pocketpro-sba-backend.onrender.com"
    routes:
      - type: rewrite
        source: /api/(.*)
        destination: https://pocketpro-sba-backend.onrender.com/api/$1
      - type: static
        source: /
        destination: /

  # Backend API Service (Primary Application)
  - type: web
    name: pocketpro-sba-backend
    runtime: python3
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 2 --timeout 120 --keepalive 2 --max-requests 1000
    envVars:
      - key: PYTHON_VERSION
        value: 3.13
      - key: FLASK_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: pocketpro-sba-backend
          property: port
    plan: free
    name: pocketpro-sba-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
        value: "1"
    healthCheckPath: /health
    healthCheckTimeout: 30
    autoDeploy: false
    numInstances: 1
