services:
  # ChromaDB Vector Database Service
  - type: web
    name: pocketpro-chromadb
    env: docker
    dockerfilePath: ./Dockerfile.chromadb
    plan: starter
    envVars:
      - key: CHROMA_HOST
        value: 0.0.0.0
      - key: CHROMA_PORT
        value: 8000
    disk:
      name: chromadb-data
      mountPath: /chroma/chroma
      sizeGB: 1

  # Backend API Service  
  - type: web
    name: pocketpro-backend
    env: docker
    dockerfilePath: ./Dockerfile.backend.prod
    plan: starter
    envVars:
      - key: FLASK_ENV
        value: production
      - key: GEMINI_API_KEY
        fromSecret: GEMINI_API_KEY
      - key: SECRET_KEY
        generateValue: true
      - key: CHROMA_HOST
        fromService:
          type: web
          name: pocketpro-chromadb
          property: host
      - key: CHROMA_PORT
        value: 8000
      - key: CORS_ORIGINS
        value: "*"
    healthCheckPath: /health

  # Frontend Static Site
  - type: static
    name: pocketpro-frontend
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/build
    envVars:
      - key: REACT_APP_BACKEND_URL
        fromService:
          type: web
          name: pocketpro-backend
          property: host
