services:
  # Backend API Service (Primary Application)
  - type: web
    name: pocketpro-sba-backend
    runtime: python
    buildCommand: pip install --upgrade pip setuptools wheel && pip install -r requirements-render.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 1 --timeout 120 run:app
    plan: starter
    envVars:
      - key: PYTHON_VERSION
        value: 3.13
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: run.py
      - key: GEMINI_API_KEY
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHONPATH
        value: /opt/render/project/src:/opt/render/project
      - key: PORT
        value: 10000
    healthCheckPath: /health
    autoDeploy: true

  # Frontend Static Site
  - type: web
    name: pocketpro-sba-frontend
    runtime: static
    buildCommand: cd frontend && npm install --legacy-peer-deps && npm run build
    staticPublishPath: frontend/build
    pullRequestPreviewsEnabled: false
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: REACT_APP_BACKEND_URL
        fromService:
          type: web
          name: pocketpro-sba-backend
          property: host
      - key: CHROMA_HOST
        fromService:
          type: web
          name: pocketpro-chromadb
          property: host
      - key: CHROMA_PORT
        value: 8000
      - key: CORS_ORIGINS
        value: "*"
    healthCheckPath: /health

  # Frontend Static Site
  - type: static
    name: pocketpro-frontend
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/build
    envVars:
      - key: REACT_APP_BACKEND_URL
        fromService:
          type: web
          name: pocketpro-backend
          property: host
