# Monitoring and Security Configuration

## Prometheus Configuration (prometheus.yml)
```yaml
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'pocketprosba'
    static_configs:
      - targets: ['backend:5000']
    metrics_path: '/metrics'
    
  - job_name: 'chromadb'
    static_configs:
      - targets: ['chromadb:8000']
    metrics_path: '/metrics'
```

## Alert Rules (alerts.yml)
```yaml
groups:
  - name: PocketProSBA
    rules:
      - alert: HighErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) > 0.1
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: High error rate detected
          
      - alert: HighLatency
        expr: http_request_duration_seconds{quantile="0.9"} > 2
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High latency detected
          
      - alert: LowDiskSpace
        expr: node_filesystem_avail_bytes{mountpoint="/data"} / node_filesystem_size_bytes{mountpoint="/data"} * 100 < 10
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: Low disk space on ChromaDB volume
```

## Security Headers (nginx.conf)
```nginx
# Security headers
add_header X-Frame-Options "SAMEORIGIN";
add_header X-XSS-Protection "1; mode=block";
add_header X-Content-Type-Options "nosniff";
add_header Referrer-Policy "strict-origin-when-cross-origin";
add_header Content-Security-Policy "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline';";
add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

# Rate limiting
limit_req_zone $binary_remote_addr zone=one:10m rate=10r/s;
limit_req zone=one burst=20 nodelay;
```

## WAF Rules (modsecurity.conf)
```apache
# Base ModSecurity rules
SecRuleEngine On
SecRequestBodyAccess On
SecResponseBodyAccess On

# SQL Injection Protection
SecRule REQUEST_COOKIES|REQUEST_COOKIES_NAMES|REQUEST_HEADERS|ARGS_NAMES|ARGS|XML:/* "@detectSQLi" \
    "id:942100,phase:2,deny,status:403,log,msg:'SQL Injection Attack'"

# XSS Protection
SecRule REQUEST_COOKIES|REQUEST_COOKIES_NAMES|REQUEST_HEADERS|ARGS_NAMES|ARGS|XML:/* "@detectXSS" \
    "id:941100,phase:2,deny,status:403,log,msg:'XSS Attack'"

# File Upload Protection
SecRule FILES_NAMES "@rx .*\.(?:php|phar|phtml|php3|php4|php5|php7|phps)$" \
    "id:400001,phase:2,deny,status:403,log,msg:'PHP File Upload Attempt'"
```

## Backup Configuration (backup.conf)
```yaml
schedule:
  chromadb_data:
    frequency: "0 2 * * *"  # Daily at 2 AM
    retention: 7  # Keep 7 days of backups
    destination: "/backups/chromadb"
    
  app_logs:
    frequency: "0 3 * * *"  # Daily at 3 AM
    retention: 14  # Keep 14 days of logs
    destination: "/backups/logs"

monitoring:
  backup_status:
    alert_on_failure: true
    notification_email: "ops@yourdomain.com"
```